version: "3"
services:
    db:
        image: mongo:3.2
        volumes:
          - ./data/db:/data/db
        expose:
          - "27017"
        ports:
        - "27017:27017"

    broker:
        image: redis
        volumes:
          - ./data/broker:/data
        expose:
          - "6379"
        ports:
          - "6379:6379"

    search:
        image: udata/elasticsearch:2.4.5
        volumes:
          - ./data/search/data:/usr/share/elasticsearch/data
        expose:
          - "9200"
        ports:
          - "9200:9200"

    flower:
      image: mher/flower
      environment:
        - CELERY_BROKER_API=redis://broker:6379/0
        - CELERY_BROKER_URL=redis://broker:6379/0
        - FLOWER_PORT=7070
      ports:
        - 7070:7070
      depends_on:
        - broker